services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ES_HOST=${ES_HOST}
      - ES_USER=${ES_USER}
      - ES_PASS=${ES_PASS}
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 10s
      retries: 3
